import { AnnounceAppErrorEntity } from "../errors/application.error"

export class subscriptions{
    private Subscription! : PurchasedSubscriptionI
    private subscriptionsTypesPrice = new Map([
        ["medium",{name:"medium",monthly_amount:9,currency:"eur",plan_description:""}],
        ["premium",{name:"premium",monthly_amount:12,currency:"eur",plan_description:""}]
    ])

    constructor(props:SubscriptionOption){
        const subscription = this.subscriptionsTypesPrice.get(props.subscriptionType)

        if(!subscription || typeof subscription == "undefined"){
            throw new AnnounceAppErrorEntity({name:"Invalid subscription",description:"the subscription so have just selected is invalid",page:"SubscriptionEntity"})
        }
        if(props.enterpriseOperationState == "inactive"){
            throw new AnnounceAppErrorEntity({name:"Account Activation issue",description:"Verify your email to activate your account or request an activation link",page:"SubscriptionEntity"})
        }
        
        this.Subscription={
            amount:subscription.monthly_amount,
            Currency:subscription.currency,
            CompanyEmail:props.companyEmail,
            CompanyId:props.companyId,
            SubscriptName:subscription.name,
            PaymentId:crypto.randomUUID().toString(),// OperationId will be generated by stripe
            description:subscription.plan_description
        }
    }
    get purchasedSubscription(){
        return{
            ...this.Subscription
        }
    }
}

type SubscriptionOption={
    companyId:string,
    companyEmail:string,
    enterpriseOperationState:"active"|"inactive",
    subscriptionType: "medium" | "premium",
}

type PurchasedSubscriptionI={
    CompanyEmail:string,
    CompanyId:string,
    SubscriptName:string,
    amount:number,
    Currency:string,
    PaymentId:string,
    description:string
}